api:
  key: 83e825b1-2bfc-4e2b-a745-66a26c2391bf

jwt:
  secret: dc7eb75c-9c87-11ed-a8fc-0242ac120002

logging:
  file: /var/www/html/smpp/storage/logs/smpp.log
  level:
    root: ERROR
    com:
      nexah: ERROR
sms:
  async:
    initial-delay: 30000
    rebind-delay: 20000

server:
  port: 8081
  tomcat:
    max-connections: 20000
    max-threads: 10000
    accept-count: 1000
    min-spare-threads: 1000
  servlet:
    contextPath: /api
    request-timeout: 60000

  #ssl:
  #  enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: production
  data:
    mongodb:
      host: 3.128.45.200
      port: 27017
      database: smpp_ocm_db
      username: smpp_ocm_user
      password: smppPwd
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false